server:
  port: 8080

spring:
  application:
    name: yellow-store
  datasource:
    # Postgres 서버 타임존을 서울(KST)로 맞추기 위해 옵션 추가
    url: ${POSTGRES_URL:}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASS:}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: ${USE_ORM_AUTO:}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  v1: api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:}
    success-url: ${TOSS_SUCCESS_URL:http://localhost:8080/payments/success.html}
    fail-url: ${TOSS_FAIL_URL:http://localhost:8080/payments/fail.html}
